# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_max_pages": "00_pubmed.ipynb",
         "request_headers": "00_pubmed.ipynb",
         "write_db": "00_pubmed.ipynb",
         "extract_page": "00_pubmed.ipynb",
         "extract_and_write": "00_pubmed.ipynb",
         "process_many": "00_pubmed.ipynb",
         "crawl_list": "00_pubmed.ipynb",
         "crawl_pubmed": "00_pubmed.ipynb"}

modules = ["pubmed.py"]

doc_url = "https://insai.github.io/research_crawler/"

git_url = "https://github.com/insai/research_crawler/tree/master/"

def custom_doc_links(name): return None
